apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-db-data
spec:
  storageClassName: mongo-db-data
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/kubernetes/mongo-db/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-db-log
spec:
  storageClassName: mongo-db-log
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/kubernetes/mongo-db/log
